[package]
name = "rusty_bar"
version = "0.1.0"
authors = ["JJWasyl <37805855+JJWasyl@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.16.0"
futures = "0.3.4"
rand = "0.7"